name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
         - TARGET: aarch64-unknown-linux-gnu
           OS: ubuntu-latest
         - TARGET: aarch64-unknown-linux-gnu
           OS: ubuntu-latest
         - TARGET: x86_64-apple-darwin
           OS: ubuntu-latest
         - TARGET: x86_64-pc-windows-gnu
           OS: ubuntu-latest
         - TARGET: x86_64-unknown-linux-gnu
           OS: ubuntu-latest
         - TARGET: aarch64-unknown-linux-musl
           OS: ubuntu-latest
         - TARGET: arm-unknown-linux-gnueabihf # raspberry pi 0-1
           OS: ubuntu-latest
         - TARGET: armv7-unknown-linux-gnueabihf # raspberry pi 2-3-4
           OS: ubuntu-latest
         - TARGET: x86_64-unknown-linux-musl
           OS: ubuntu-latest
    runs-on: ${{ matrix.OS }}
    steps:
    - uses: actions/checkout@v2
    - name: Install and configure dependencies
      run: |
        sudo apt-get install -qq gcc-arm-linux-gnueabihf
        
        cat >>~/.cargo/config <<EOF
        [target.armv7-unknown-linux-gnueabihf]
        linker = "arm-linux-gnueabihf-gcc"
        [target.arm-unknown-linux-musleabihf]
        linker = "arm-linux-gnueabihf-gcc"
        EOF
    - name: Install rust target
      run: rustup target add ${{ matrix.TARGET }}
    - name: Run build
      run: cargo build --release --verbose --target ${{ matrix.TARGET }}