name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [
          aarch64-unknown-linux-gnu,
          x86_64-apple-darwin,
          x86_64-pc-windows-gnu,
          x86_64-unknown-linux-gnu,
          aarch64-unknown-linux-musl,
          armv7-unknown-linux-gnueabihf,
          x86_64-unknown-linux-musl
        ]
    steps:
    - uses: actions/checkout@v2
    - name: Install and configure cross-compile tools
      run: |
sudo apt-get install -qq gcc-arm-linux-gnueabihf
cat >>~/.cargo/config <<EOF
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
EOF
...
    - name: Install rust target
      run: rustup target add ${{ matrix.target }}
    - name: Run build
      run: cargo build --release --verbose --target ${{ matrix.target }}